const getters = {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  loading: state => state.app.loading,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  cachedViews: state => state.tagsView.cachedViews,
  roles: state => state.user.roles,
  grade: state => state.user.grade,
  roleId: state => state.user.roleId,
  roleObj: state => state.user.roleObj,
  oemName: state => state.user.oemName,
  OEMlist: state => state.user.OEMlist,
  brandId: state => state.user.brandId,
  phone: state => state.user.phone,
  dfPhone: state => state.user.dfPhone,
  TRXchannellist: state => state.user.TRXchannellist,
  companyname: state => state.user.companyname,
  ShopType: state => state.user.ShopType,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  managementTool: state => state.user.managementTool,
}
export default getters
